title:              CyberSpace
email:              electroboy404notfound@gmail.com
description:        A Place for All things Cyber
author:             CyberSpaceStudios
baseurl:            "/blog"
url:                "https://cyberspacestudios.github.io"

# Social Profiles
twitter_username:   
github_username:    CyberSpaceStudios
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-TZVS60BBYT # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
